"""add_tool_call_fields_to_messages

Revision ID: 2d4250f2e651
Revises: 20260524_000002
Create Date: 2026-05-25 15:26:58.064562
"""
from alembic import op
import sqlalchemy as sa



# revision identifiers, used by Alembic.
revision = '2d4250f2e651'
down_revision = '20260524_000002'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('messages', sa.Column('tool_call', sa.Boolean(), server_default='false', nullable=False))
    op.add_column('messages', sa.Column('tool_name', sa.String(length=120), nullable=True))
    op.add_column('messages', sa.Column('tool_action', sa.String(length=255), nullable=True))
    op.add_column('messages', sa.Column('tool_result', sa.Text(), nullable=True))
    op.drop_constraint(op.f('uq_organizations_clerk_org_id'), 'organizations', type_='unique')
    op.drop_index(op.f('ix_organizations_clerk_org_id'), table_name='organizations')
    op.create_index(op.f('ix_organizations_clerk_org_id'), 'organizations', ['clerk_org_id'], unique=True)
    op.drop_constraint(op.f('uq_users_clerk_user_id'), 'users', type_='unique')
    op.drop_index(op.f('ix_users_clerk_user_id'), table_name='users')
    op.create_index(op.f('ix_users_clerk_user_id'), 'users', ['clerk_user_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_clerk_user_id'), table_name='users')
    op.create_index(op.f('ix_users_clerk_user_id'), 'users', ['clerk_user_id'], unique=False)
    op.create_unique_constraint(op.f('uq_users_clerk_user_id'), 'users', ['clerk_user_id'], postgresql_nulls_not_distinct=False)
    op.drop_index(op.f('ix_organizations_clerk_org_id'), table_name='organizations')
    op.create_index(op.f('ix_organizations_clerk_org_id'), 'organizations', ['clerk_org_id'], unique=False)
    op.create_unique_constraint(op.f('uq_organizations_clerk_org_id'), 'organizations', ['clerk_org_id'], postgresql_nulls_not_distinct=False)
    op.drop_column('messages', 'tool_result')
    op.drop_column('messages', 'tool_action')
    op.drop_column('messages', 'tool_name')
    op.drop_column('messages', 'tool_call')
    # ### end Alembic commands ###
