"""add logo_url to organizations

Revision ID: e32ecbc54f42
Revises: 7a1b9c2d3e4f
Create Date: 2026-07-14 15:24:06.576609
"""
from alembic import op
import sqlalchemy as sa



# revision identifiers, used by Alembic.
revision = 'e32ecbc54f42'
down_revision = '7a1b9c2d3e4f'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('billing_events', 'org_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.drop_index(op.f('idx_conversations_created_at'), table_name='conversations')
    op.drop_index(op.f('idx_conversations_org_agent_user'), table_name='conversations')
    op.alter_column('organizations', 'logo_url',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('organizations', 'logo_url',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.create_index(op.f('idx_conversations_org_agent_user'), 'conversations', ['org_id', 'agent_id', 'user_id'], unique=False)
    op.create_index(op.f('idx_conversations_created_at'), 'conversations', [sa.literal_column('created_at DESC')], unique=False)
    op.alter_column('billing_events', 'org_id',
               existing_type=sa.UUID(),
               nullable=False)
    # ### end Alembic commands ###
