"""add category to integrations

Revision ID: e9d6a28b89a5
Revises: 2d4250f2e651
Create Date: 2026-05-26 13:29:16.397940
"""
from alembic import op
import sqlalchemy as sa



# revision identifiers, used by Alembic.
revision = 'e9d6a28b89a5'
down_revision = '2d4250f2e651'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('integrations', sa.Column('category', sa.String(length=100), nullable=True))
    op.create_index(op.f('ix_integrations_category'), 'integrations', ['category'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_integrations_category'), table_name='integrations')
    op.drop_column('integrations', 'category')
    # ### end Alembic commands ###
